
import './style.css'
import { listRecipes, getRecipe, createRecipe, updateRecipe, deleteRecipe } from './features/recipesStore.js'
import { registerSW } from './sw-register'
registerSW()
const app=document.getElementById('app')
const el=(t,a={},...c)=>{const n=document.createElement(t);for(const[k,v]of Object.entries(a)){if(k==='class')n.className=v;else if(k in n)n[k]=v;else n.setAttribute(k,v)}for(const x of c){if(x==null)continue;typeof x==='string'?n.appendChild(document.createTextNode(x)):n.appendChild(x)}return n}
const parseLines=t=>t.split('\n').map(s=>s.trim()).filter(Boolean)
const parseIngredients=t=>parseLines(t).map(line=>({id:crypto.randomUUID(),text:line}))
const ingredientsToText=a=>(a||[]).map(x=>x.text).join('\n')
const stepsToText=a=>(a||[]).join('\n')
function listView(){const items=listRecipes();const header=el('div',{class:'toolbar'},el('a',{href:'/'},'🏠 Meny'),' ',el('a',{href:'/list.html'},'🧾 Inköpslista'),' ',el('a',{href:'#new',class:'btn'},'➕ Nytt recept'));const ul=el('ul',{class:'recipes-list'});items.forEach(r=>{ul.appendChild(el('li',{},el('strong',{},r.title),' ',el('small',{},`(för ${r.portion})`),' ',el('button',{onclick:()=>location.hash='edit:'+r.id},'✏️ Redigera'),el('button',{onclick:()=>{if(confirm('Ta bort?')){deleteRecipe(r.id);render()}}},'🗑️ Ta bort')))});return el('section',{},header,ul,items.length===0?el('p',{},'Inga recept ännu.'):null)}
function formView(mode,id){const rec=mode==='edit'?getRecipe(id):{title:'',portion:4,tags:[],ingredients:[],steps:[]};if(mode==='edit'&&!rec)return el('p',{},'Recept hittas inte.');const title=el('input',{placeholder:'Titel',value:rec.title||''});const portion=el('input',{type:'number',min:1,value:rec.portion||4});const tags=el('input',{placeholder:'Taggar (kommaseparerat)',value:(rec.tags||[]).join(', ')});const ing=el('textarea',{rows:8,placeholder:'Ingredienser, en per rad',value:ingredientsToText(rec.ingredients)});const steps=el('textarea',{rows:8,placeholder:'Steg, en per rad',value:stepsToText(rec.steps)});const saveBtn=el('button',{class:'btn-primary'},'💾 Spara');saveBtn.onclick=()=>{const data={title:title.value.trim(),portion:Number(portion.value||4),tags:tags.value.split(',').map(s=>s.trim()).filter(Boolean),ingredients:parseIngredients(ing.value),steps:parseLines(steps.value)};if(!data.title){alert('Titel krävs');return}if(mode==='new')createRecipe(data);else updateRecipe(rec.id,data);location.hash='';render()};const cancelBtn=el('button',{},'Avbryt');cancelBtn.onclick=()=>{location.hash='';render()};return el('section',{class:'form'},el('p',{},el('a',{href:'#'},'← Tillbaka')),el('label',{},'Titel',title),el('label',{},'Portioner',portion),el('label',{},'Taggar',tags),el('label',{},'Ingredienser',ing),el('label',{},'Steg',steps),el('div',{},saveBtn,' ',cancelBtn))}
function render(){app.textContent='';const h=location.hash.slice(1);if(!h)app.appendChild(listView());else if(h==='new')app.appendChild(formView('new'));else if(h.startsWith('edit:'))app.appendChild(formView('edit',h.split(':')[1]))}
window.addEventListener('hashchange',render);render()
